import type { CategoryId } from "../categories";

export const priorityConfig = {
  levels: {
    critical: 75,
    high: 50,
    medium: 25
  },
  riskCategoryIds: ["electronics"] satisfies CategoryId[],
  urgentKeywords: [
    "refund",
    "return",
    "broken",
    "damaged",
    "wrong",
    "missing",
    "cancel",
    "claim",
    "urgent",
    "late",
    "not arrived",
    "devolucion",
    "reembolso",
    "devolver",
    "reintegro",
    "problema",
    "reclamo",
    "roto",
    "rota",
    "rotos",
    "rotas",
    "danado",
    "danada",
    "danados",
    "danadas",
    "falla",
    "fallo",
    "defectuoso",
    "defectuosa",
    "no funciona",
    "equivocado",
    "equivocada",
    "incorrecto",
    "incorrecta",
    "cancelar",
    "cancelacion",
    "urgente",
    "no recibi",
    "falta"
  ],
  shippingKeywords: [
    "shipping",
    "delivery",
    "delivered",
    "address",
    "envio",
    "entrega",
    "despacho",
    "seguimiento",
    "direccion",
    "domicilio",
    "paquete",
    "no llego",
    "correo",
    "transportista",
    "demora",
    "demorado",
    "tarde"
  ]
} as const;
